;angular.module('BB').constant('BB_ENGLISH_TRANSLATIONS', {
  "CHANGE_LANG":"Change language",
  "EN":"English",
  "DE":"Deutsch",
  "FR":"Français",
  "POWERED_BY":"Bookings powered by",
  "DASHBOARD":"Dashboard",
  "DASHBOARD_TITLE":"Pick a Location/Service",
  "PROGRESS_BAR_TITLE":"Step",
  "PROGRESS_BAR_COMPLETE":"Complete",
  "PROGRESS_BACK":"Back",
  "PROGRESS_PREVIOUS":"Previous",
  "PROGRESS_CANCEL":"Cancel",
  "PROGRESS_CLEAR":"Clear",
  "PROGRESS_SEARCH":"Search",
  "PROGRESS_SELECT":"Select",
  "PROGRESS_CONFIRM":"Confirm",
  "PROGRESS_NEXT":"Next",
  "PROGRESS_CONTINUE":"Continue",
  "PROGRESS_BOOK":"Book",
  "PROGRESS_BOOK_WAITLIST_ITEMS":"Book Waitlist Items",
  "PROGRESS_ADD":"Add",
  "PROGRESS_BUY":"Buy",
  "PROGRESS_RESERVE":"Reserve",
  "PROGRESS_APPLY":"Apply",
  "PROGRESS_REMOVE":"Remove",
  "PROGRESS_OK":"OK",
  "PROGRESS_MOVE_BOOKING":"Move booking",
  "PROGRESS_CANCEL_CANCEL":"Do not cancel",
  "PROGRESS_CANCEL_BOOKING":"Cancel booking",
  "MAP_TITLE":"Search for a store to begin your booking.",
  "MAP_PLACEHOLDER":"Enter a town, city, postcode or store",
  "GEOLOCATE":"Use current location",
  "STORE_RESULT_TITLE":"{results, plural, =0{No results} one{1 result} other{# results}} for stores near {address}",
  "STORE_PHONE":"Phone",
  "PICK_A_SERVICE":"pick a service",
  "PICK_AN_ADVISER":"pick an adviser",
  "PICK_A_RESOURCE":"pick a resource",
  "AVAIL_TITLE":"Select a date and time for your {{ current_item }} appointment.",
  "AVAIL_DAY_PREVIOUS":"Previous Day",
  "AVAIL_DAY_NEXT":"Next Day",
  "AVAIL_MONTH_PREVIOUS":"Previous Month",
  "AVAIL_MONTH_NEXT":"Next Month",
  "AVAIL_MORNING":"Morning",
  "AVAIL_AFTERNOON":"Afternoon",
  "AVAIL_EVENING":"Evening",
  "AVAILABLE":"{number, plural, =0{None available} other{# available}}",
  "AVAIL_NO":"No Service Available",
  "PICK_A_DATE":"Pick a date",
  "HOUR":"hour",
  "MIN":"min",
  "AND":"and",
  "AT":"at",
  "FILTER":"Filter",
  "FILTER_ANY":"Any ",
  "FILTER_CATEGORY":"Category",
  "FILTER_FILTERED":"Showing filtered events",
  "FILTER_NONE":"Showing all events",
  "FILTER_RESET":"Reset",
  "SERVICE_LIST_NO":"No services match your filter criteria.",
  "ITEM":"Item",
  "ITEM_SERVICE":"Service",
  "ITEM_RESOURCE":"Resource",
  "ITEM_PERSON":"Person",
  "ITEM_PRICE":"Price",
  "ITEM_DUE_NOW":"Due Now",
  "ITEM_FREE":"Free",
  "ITEM_DATE":"Date",
  "ITEM_TIME":"Time",
  "ITEM_DATE_AND_OR_TIME":"Date/Time",
  "ITEM_SESSION":"Session",
  "ITEM_DURATION":"Duration",
  "ITEM_QTY":"Qty",
  "ITEM_QUANTITY":"Quantity",
  "ITEM_TYPE":"Type",
  "ITEM_WHEN":"When",
  "ITEM_WHERE":"Where",
  "ITEM_FROM":"From",
  "ITEM_DESCRIPTION":"Description",
  "ITEM_CONFIRMATION":"Confirmation",
  "EVENT_DETAILS_TITLE":" Event details",
  "EVENT_WORD":"Events",
  "EVENT_LOCATION":"Events at",
  "EVENT_NO":"No events found",
  "EVENT_SOLD_OUT":"Sold out",
  "EVENT_SOLD_OUT_HIDE":"Hide Sold Out Events",
  "EVENT_SOLD_OUT_SHOW":"Show Sold Out Events",
  "EVENT_TICKET":"ticket",
  "EVENT_TICKET_SUMMARY_TITLE":"Ticket Summary",
  "EVENT_TICKETS":"Tickets",
  "EVENT_SPACE_WORD":"space",
  "EVENT_LEFT_WORD":"left",
  "EVENT_SPACES_REMAINING":"remaining",
  "EVENT_JOIN_WAITLIST":"Join Waitlist",
  "EVENT_PAYMENT":"Please complete payment to confirm your booking",
  "WAITLIST_BOOKING_TITLE":"Your Waitlist booking",
  "BASKET_TITLE":"Your basket",
  "BASKET_WALLET":"Wallet",
  "BASKET_WALLET_BALANCE":"Current Wallet Balance",
  "BASKET_WALLET_BALANCE_INSUFFICIENT":"Oh no! You do not currently have enough money in your wallet account. You can either pay the full amount, or top up to add more money to your wallet.",
  "BASKET_WALLET_REMAINDER_PART_ONE":"You will have",
  "BASKET_WALLET_REMAINDER_PART_TWO":"left in your wallet after this purchase",
  "BASKET_WALLET_TOP_UP":"Top Up",
  "BASKET_WALLET_MAKE_PAYMENT":"Make Payment",
  "BASKET_WALLET_AMOUNT":"Amount",
  "BASKET_WALLET_AMOUNT_MINIMUM":"Minimum top up amount must be greater than",
  "BASKET_ADD":"Add to Basket",
  "BASKET_BOOKING_FEE":"Booking Fee",
  "BASKET_CHECKOUT":"Checkout",
  "BASKET_DISCOUNT":"Discount",
  "BASKET_COUPON_DISCOUNT":"Coupon Discount",
  "BASKET_COUPON_APPLY":"Apply a coupon",
  "BASKET_CERTIFICATE_PAID":"Certificate Paid",
  "BASKET_DETAILS_TITLE":"Basket Details",
  "BASKET_DETAILS_NO":"No items added to basket yet.",
  "BASKET_ITEM_APPOINTMENT":"Appointment",
  "BASKET_ITEM_ADD":"Add another item",
  "BASKET_ITEM_NO":"There are no items in the basket",
  "BASKET_ITEM_ADD_INSTRUCT":"Please press the add another item button if you wish to add a product or service.",
  "BASKET_GIFT_CERTIFICATE":"Gift Certificates",
  "BASKET_GIFT_CERTIFICATE_APPLY":"Apply a Gift Certificate",
  "BASKET_GIFT_CERTIFICATE_APPLY_ANOTHER":"Apply another Gift Certificate",
  "BASKET_GIFT_CERTIFICATE_APPLIED":"Gift Certificates applied",
  "BASKET_GIFT_CERTIFICATE_BUY":"Buy Gift Certificates",
  "BASKET_GIFT_CERTIFICATE_QUESTION":"Have a gift certificate?",
  "BASKET_GIFT_CERTIFICATE_TOTAL":"Total Gift Certificates",
  "BASKET_GIFT_CERTIFICATE_BALANCE":"Remaining Value on Gift Certificate",
  "BASKET_GIFT_CERTIFICATE_SELECTED": "Selected Gift Certificates",
  "BASKET_PRICE_ORIGINAL":"Original Price",
  "BASKET_SUBTOTAL":"Subtotal",
  "BASKET_TOTAL":"Total",
  "BASKET_TOTAL_DUE_NOW":"Total Due Now",
  "REVIEW_TITLE":"Review your appointment details",
  "DETAILS_TITLE":"Your details",
  "DETAILS_WORD":"Details",
  "DETAILS_FIRST_NAME":"First Name",
  "DETAILS_FIRST_NAME_VALIDATION_MSG":"Please enter your first name",
  "DETAILS_LAST_NAME":"Last Name",
  "DETAILS_LAST_NAME_VALIDATION_MSG":"Please enter your last name",
  "DETAILS_EMAIL":"E-mail",
  "DETAILS_EMAIL_VALIDATION_MSG":"Please enter a valid email address",
  "DETAILS_PHONE_MOBILE":"Mobile",
  "DETAILS_PHONE_MOBILE_VALIDATION_MSG":"Please enter a valid mobile number",
  "DETAILS_ADDRESS":"Address",
  "DETAILS_TOWN":"Town",
  "DETAILS_COUNTY":"County",
  "DETAILS_POSTCODE":"Postcode",
  "DETAILS_TERMS":" I agree to the terms and conditions",
  "DETAILS_TERMS_VALIDATION_MSG":"Please accept the terms and conditions",
  "DETAILS_VALIDATION_MSG":"This field is required",
  "DETAILS_REQUIRED":"Required",
  "DETAILS_OPTIONAL":"optional",
  "DETAILS_OTHER_INFO":"Other information",
  "DETAILS_QUESTIONS":"Questions",
  "CLIENT_DETAILS_TITLE":"Client details",
  "CLIENT_DETAILS_INSTRUCTION":"Search for a customer or create a new one",
  "CLIENT_DETAILS_SEARCH":"Search for a customer",
  "CLIENT_DETAILS_SEARCH_BY_NAME_OR_EMAIL":"Search by Name or Email",
  "CLIENT_DETAILS_SEARCH_ERROR":"Sorry, your search must be more than 3 characters long",
  "CLIENT_DETAILS_ENTER":"Enter customer details",
  "CLIENT_DETAILS_FIRST_NAME":"Please enter the client's first name",
  "CLIENT_DETAILS_LAST_NAME":"Please enter the client's last name",
  "CLIENT_DETAILS_CREATE":"Create Client",
  "CLIENT_BOOKING_NOTES":"Booking Notes",
  "ATTENDEE":"Attendee",
  "ATTENDEE_FIRST_NAME_VALIDATION_MSG":"Please enter a first name for this attendee",
  "ATTENDEE_LAST_NAME_VALIDATION_MSG":"Please enter last name for this attendee",
  "ATTENDEE_EMAIL_VALIDATION_MSG":"Please enter a valid email address for this attendee",
  "ATTENDEE_IS_YOU_QUESTION":"Are you the attendee?",
  "ATTENDEE_USE_MY_DETAILS":" Yes, use my details",
  "RECIPIENT":"Recipient",
  "RECIPIENT_ADD":"Add a Recipient",
  "RECIPIENT_TO":"Who should we send the gift voucher to?",
  "RECIPIENT_ME":"Me",
  "RECIPIENT_NOT_ME":"Someone else",
  "RECIPIENT_NAME":"Name",
  "RECIPIENT_NAME_VALIDATION_MSG":"Please enter the recipient's full name",
  "RECIPIENT_EMAIL_VALIDATION_MSG":"Please enter a valid email address",
  "MEMBERSHIP_TYPES":"Membership Types",
  "PAYMENT_WORD":"Payment",
  "PAYMENT_DETAILS_TITLE":"Payment Details",
  "PAYMENT_INSTRUCTION":"Please enter your payment details to confirm your booking.",
  "NEWSLETTER":"Sign up to our email newsletter and be first to hear about events, news and inspiration.",
  "REVIEW":"Review",
  "CONFIRMATION_BOOKING_TITLE":"Booking Confirmation",
  "CONFIRMATION_BOOKING_SUBHEADER":"Thanks {{ member_name }}. Your booking is now confirmed. We have emailed you the details below.",
  "CONFIRMATION_BOOKING_SUBHEADER_WITH_WAITLIST":"Thanks {{ member_name }}. Your have successfully made the following bookings. We have you emailed you the details below.",
  "CONFIRMATION_PAYMENT_TITLE":"Payment Confirmation",
  "CONFIRMATION_PAYMENT_SUBHEADER":"Thanks {{ member_name }}. Your payment was successful. We have you emailed you the details below.",
  "CONFIRMATION_PURCHASE_TITLE":"Your {{ service_name }} booking",
  "CONFIRMATION_WAITLIST_SUBHEADER":"Thanks {{ member_name }}. You have successully booked onto {{ purchase_item }}.", 
  "CONFIRMATION_INSPIRATION_LINK":"Visit our inspiration site",
  "CONFIRMATION_HOMEPAGE_LINK":"Return to the homepage",
  "BOOKING_REFERENCE":"Booking Reference",
  "PRINT":" Print",
  "CALENDAR_EXPORT_TITLE":" Export to calendar",
  "CANCEL_QUESTION":"Are you sure you want to cancel this booking?",
  "CANCEL_CONFIRMATION":"Your booking has been cancelled.",
  "RESULTS":"Results",
  "PLEASE_TRY_AGAIN":"Please try again",
  "ADD_ONS":"Add-ons",
  "SURVEY_WORD":"Survey",
  "SURVEY_NO":"No survey questions for this session.",
  "SURVEY_SUBMIT":"Submit Answers",
  "SURVEY_THANK_YOU":"Thank you for filling out the survey!",
  "ERROR":{
    "GENERIC":"Sorry, it appears that something went wrong. Please try again or call the business you're booking with if the problem persists.",
    "LOCATION_NOT_FOUND":"Sorry, we don't recognise that location",
    "MISSING_LOCATION":"Please enter your location",
    "MISSING_POSTCODE":"Please enter a postcode",
    "INVALID_POSTCODE":"Please enter a valid postcode",
    "ITEM_NO_LONGER_AVAILABLE":"Sorry. The item you were trying to book is no longer available. Please try again.",
    "FORM_INVALID":"Please complete all required fields",
    "GEOLOCATION_ERROR":"Sorry, we could not determine your location. Please try searching instead.",
    "EMPTY_BASKET_FOR_CHECKOUT":"There are no items in the basket to proceed to checkout."
  },
  "THOUSANDS_SEPARATOR": ",",
  "DECIMAL_SEPARATOR": ".",
  "CURRENCY_FORMAT": "%s%v",
  "TIME_SEPARATOR": " and ",
  "PASSWORD": "Password",
  "LOG_IN": "Log in",
  "NEW_BOOKING": "New booking",
  "EDIT": "Edit",
  "SAVE_BOOKING": "Save booking",
  "DISMISS": "Dismiss",
  "BOOKING": "Booking",
  "EMAIL_CUSTOMER_QUESTION": "Email customer?",
  "CLOSE": "Close",
  "UPCOMING_BOOKINGS": "Upcoming bookings",
  "PAST_BOOKINGS": "Past bookings",
  "PURCHASES": "Purchases",
  "NO_PAST_BOOKINGS": "You don't currently have any past bookings.",
  "NO_PREPAID_BOOKINGS": "You don't currently have any pre-paid bookings.",
  "REMAINING_BOOKINGS": "{{remaining}} of {{total}} remaining",
  "YOUR_PURCHASES": "Your Purchases",
  "NO_CURRENT_PURCHASES": "You don't currently have any purchases",
  "PURCHASE_REF": "Purchase Ref",
  "NO_UPCOMING_BOOKINGS": "You don't currently have any upcoming bookings.",
  "PICK_COMPANY": "Pick Company",
  "WALLET_TRANSACTION_HISTORY": "Wallet Transaction History",
  "ACTION": "Action",
  "AMOUNT": "Amount",
  "BALANCE": "Balance",
  "CHANGED_BY": "Changed By",
  "DATE_AND_TIME": "Date and Time",
  "WALLET_PURCHASE_BANDS": "Wallet Purchase Bands",
  "WALLET_NO_CREDIT": "You dont have any credit in your wallet.",
  "WALLET_NOT_ACTIVE": "Your wallet is not active.",
  "ACTIVATE": "Activate",
  "ACTIVE": "Active",
  "STATUS": "Status",
  "TOP_UP": "Top Up",
  "MIN_TOP_UP": "Minimum top up amount must be greater than {{amount | currency }}",
  "TOP_UP_WALLET": "Top up wallet by {{amount | currency}}",
  "MAKE_PAYMENT": "Make Payment",
  "$X_FOR_$Y": "{{x | currency}} for {{y | currency}}",
  "YES": "Yes",
  "NO": "No",
  "NEW_EVENT_CHAIN": "New Event Chain",
  "NEW_EVENT_GROUP": "New Event Group",
  "DELETE": "Delete",
  "NEW_ADMINISTRATOR": "New Administrator",
  "SCHEDULE": "Schedule",
  "NEW_PERSON": "New Person",
  "NEW_RESOURCE": "New Resource",
  "NEW_SERVICE": "New Service"
});
